EXPLAIN SELECT * FROM READERS WHERE FIRSTNAME = "John";
CREATE INDEX BOOKS_TITLE ON BOOKS (TITLE);
CREATE INDEX READERS_FIRSTANDLASTNAME ON READERS (FIRSTNAME, LASTNAME);
EXPLAIN SELECT * FROM READERS WHERE FIRSTNAME = "John";