CREATE TABLE STATS (
                       STAT_ID INT(11) AUTO_INCREMENT,
                       STAT_DATE DATETIME NOT NULL,
                       STAT VARCHAR(20) NOT NULL,
                       VALUE INT(11) NOT NULL,
                       PRIMARY KEY (STAT_ID)
);

CREATE VIEW BESTSELLERS_COUNT_VIEW AS
    SELECT COUNT(*) AS BESTSELLERS_COUNT FROM BOOKS
    WHERE BESTSELLER = true;

DELIMITER $$

CREATE FUNCTION NumberOfBestsellers() RETURNS INT NOT DETERMINISTIC
BEGIN
    DECLARE bestsellers INT DEFAULT 0;
    SELECT * FROM BESTSELLERS_COUNT_VIEW INTO bestsellers;
    RETURN bestsellers;
END $$

CREATE EVENT UPDATE_BESTSELLERS
ON SCHEDULE EVERY 1 MINUTE
DO BEGIN
    CALL UpdateBestsellers();
    INSERT INTO STATS(STAT_DATE, STAT, VALUE)
        VALUE (CURDATE(), "BESTSELLERS", NumberOfBestsellers());
    COMMIT;
END $$

DELIMITER ;