ALTER TABLE BOOKS ADD BESTSELLER BOOLEAN
    DEFAULT 0;
COMMIT;

DROP PROCEDURE IF EXISTS UpdateBestsellers;

DELIMITER $$

CREATE PROCEDURE UpdateBestsellers()
BEGIN
    DECLARE READCOUNT, B_ID INT;
    DECLARE FINISHED INT DEFAULT 0;
    DECLARE ALL_BOOKS CURSOR FOR SELECT BOOK_ID FROM BOOKS;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET FINISHED = 1;
    OPEN ALL_BOOKS;
    WHILE (FINISHED = 0) DO
        FETCH ALL_BOOKS INTO B_ID;
        IF FINISHED = 0 THEN
            SELECT COUNT(*) FROM RENTS
                WHERE BOOK_ID = B_ID AND
                    DATEDIFF(RENT_DATE, NOW()) <= 30
                INTO READCOUNT;
            IF READCOUNT >= 2 THEN
                UPDATE BOOKS SET BESTSELLER = true
                    WHERE BOOK_ID = B_ID;
                COMMIT;
            END IF;
        END IF;
    END WHILE;
CLOSE ALL_BOOKS;
END $$

DELIMITER ;

CALL UpdateBestsellers();

SELECT * FROM BOOKS;